version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build.sh
  build-and-deploy:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build.sh
      - run: ./login.sh
      - run: ./deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
