name: Deploy Snapshots
on:
  schedule:
    - cron: "0 0/6 * * *"
jobs:
  build:
    name: "Build, test & deploy snapshot images"
    runs-on: ubuntu-latest
    environment: deployment
    steps:
    - uses: actions/checkout@master
    - run: ./build.sh snapshot
    - run: ./test.sh
    - run: ./login.sh
      env:
        DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_USERNAME }}
        DOCKER_USER_PASSWORD: ${{ secrets.DOCKER_USER_PASSWORD }}
    - run: ./deploy.sh
