name: Build & Test PR
on: [pull_request]
jobs:
  build:
    name: "Build & test images (${{ matrix.series }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        series: [7x, 8x, snapshot]
    steps:
    - uses: actions/checkout@master
    - run: ./build.sh ${{ matrix.series }}
    - run: ./test.sh
