name: CI
on: [push, pull_request]
jobs:
  build:
    name: "Build & test images (${{ matrix.series }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        series: [6x, 7x, 8x]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: ./build.sh ${{ matrix.series }}

    - name: Test
      run: ./test.sh

    - name: Login
      run: ./login.sh
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        DOCKER_USER_USERNAME: ${{ github.secrets.DOCKER_USER_USERNAME }}
        DOCKER_USER_PASSWORD: ${{ github.secrets.DOCKER_USER_PASSWORD }}

    - name: Deploy
      run: ./deploy.sh
      if: ${{ github.ref == 'refs/heads/master' }}
