name: CI
on: [push]
jobs:
  build:
    name: "Build & test images"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: ./build.sh

    - name: Test
      run: ./test.sh
